version: '3.8'

services:
  react-app:
    build: ./react-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - alloy

  alloy:
    image: grafana/alloy:latest
    ports:
      - "4318:4318"
    volumes:
      - ./alloy/alloy.config:/etc/alloy/config.alloy
    command: --config.file=/etc/alloy/config.alloy

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
