version: '3'

services:
  alloy:
    image: grafana/agent:latest
    volumes:
      - ./alloy-config.yml:/etc/grafana-agent/config.yaml
      - ./logs:/var/log/faro
    ports:
      - "12347:12347"
    command: ["--config.file=/etc/grafana-agent/config.yaml"]
    networks:
      - monitoring-net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring-net

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana-enterprise:latest
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge

volumes:
  grafana-storage:
